SELECT * FROM A16438.STRATEGIC_DEP_PRCNG_CORE_RES SRC_RSRV
LEFT JOIN (SELECT CUST_ID AS CUST_ID2, CUST_TP FROM EDW.CUST) edw_cust 
ON SRC_RSRV.CUST_ID = edw_cust.CUST_ID2
LEFT JOIN (SELECT ASOFDATE AS MARKET_MAX_DATE, MARKET_MAX_RT FROM A16438.DEP_SMALL_APP_PARAMS) market_max
ON SRC_RSRV.CREATE_DT = market_max.MARKET_MAX_DATE
WHERE CREATE_DT >= TO_DATE('25/11/2025', 'DD/MM/YYYY')