"""Migration 0001 — Phase 6.5 semantic-tag allow-list → Phase 7 concept skeletons.

Emits ``global.yaml`` + ``treasury.yaml`` skeletons from
``SEMANTIC_TAGS_V0`` (spec §6.1 step 2). Each v0 tag becomes a concept with:

- ``id``  = the tag string (direct copy — this is the migration key, §6.2),
- ``name`` / ``description`` from the Turkish label/help tables,
- a ``type`` inferred from the tag (time tags → ``time``, ``maturity`` →
  ``bucket``, ``other`` → ``scalar``, the rest → ``enum``),
- **empty** ``canonical_values`` for enum/bucket — the data team fills these
  in via PR. The compiler degrades gracefully on empty alphabets (§6.3).

This migration is **skeleton-only**: it does NOT touch blocks, dashboards or
table docs (those are later migration steps / sub-phases). It is idempotent —
running it twice produces byte-identical YAML — and non-destructive (it writes
fresh skeletons; it never edits hand-curated concept files in place, so the
CLI refuses to overwrite unless ``--force`` is given).

Usage:
    python -m presentations.concepts.migrations.0001_v0_to_v1 <out_dir> [--force]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

from presentations.variables.semantic_tags import (
    SEMANTIC_TAGS_V0,
    describe_tag,
    tag_description,
)


# Which scope each v0 tag migrates into. Tags absent here default to global.
_DEPT_TREASURY: set[str] = {
    "maturity",
    "tenor_bucket",
    "branch",
    "region",
    "product_group",
    "segment",
    "rating_bucket",
}

# Tag → concept type. Time tags are parameterized (no value alphabet);
# maturity buckets carry day-ranges; "other" is the catch-all scalar.
_TIME_TAGS: set[str] = {"as_of_time", "trade_time", "value_time", "settle_time"}
_BUCKET_TAGS: set[str] = {"maturity"}
_SCALAR_TAGS: set[str] = {"other"}


def _concept_type(tag: str) -> str:
    if tag in _TIME_TAGS:
        return "time"
    if tag in _BUCKET_TAGS:
        return "bucket"
    if tag in _SCALAR_TAGS:
        return "scalar"
    return "enum"


def _concept_skeleton(tag: str) -> dict[str, Any]:
    ctype = _concept_type(tag)
    out: dict[str, Any] = {
        "id": tag,
        "name": describe_tag(tag),
        "type": ctype,
    }
    desc = tag_description(tag)
    if desc:
        out["description"] = desc
    if ctype == "time":
        out["granularity_default"] = "day"
    elif ctype in ("enum", "bucket"):
        # Empty alphabet — data team fills via PR. Explicit [] flags the slot.
        out["canonical_values"] = []
    return out


def build_skeleton_files() -> dict[str, dict[str, Any]]:
    """Return ``{filename_stem: concept_file_dict}`` for the skeletons.

    Two files: ``global`` and ``treasury``. Tags are partitioned by
    :data:`_DEPT_TREASURY`. Concept order within each file follows
    ``sorted(tags)`` so the output is deterministic.
    """
    global_concepts: list[dict[str, Any]] = []
    treasury_concepts: list[dict[str, Any]] = []
    for tag in sorted(SEMANTIC_TAGS_V0):
        skel = _concept_skeleton(tag)
        if tag in _DEPT_TREASURY:
            treasury_concepts.append(skel)
        else:
            global_concepts.append(skel)

    return {
        "global": {
            "version": 1,
            "scope": "global",
            "owners": {
                "department": "data_platform",
                "contact": "data.platform@qnbfb.com",
            },
            "concepts": global_concepts,
        },
        "treasury": {
            "version": 1,
            "scope": "dept:treasury",
            "owners": {
                "department": "treasury_data",
                "contact": "treasury.data@qnbfb.com",
            },
            "concepts": treasury_concepts,
        },
    }


def _dump_yaml(data: dict[str, Any]) -> str:
    header = (
        "# AUTO-GENERATED by migration 0001_v0_to_v1 from SEMANTIC_TAGS_V0.\n"
        "# Skeleton only — the data team fills in canonical_values via PR.\n"
        "# Safe to hand-edit AFTER generation; re-running the migration with\n"
        "# --force overwrites, so curate a copy or use --force deliberately.\n"
    )
    body = yaml.safe_dump(
        data, allow_unicode=True, sort_keys=False, default_flow_style=False
    )
    return header + body


def emit_skeletons(out_dir: str | Path, *, force: bool = False) -> list[Path]:
    """Write ``global.yaml`` + ``treasury.yaml`` into ``out_dir``.

    Refuses to overwrite an existing file unless ``force=True``. Returns the
    list of paths written.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    files = build_skeleton_files()
    written: list[Path] = []
    for stem, data in files.items():
        path = out_dir / f"{stem}.yaml"
        if path.exists() and not force:
            raise FileExistsError(
                f"{path} already exists; pass force=True to overwrite"
            )
        path.write_text(_dump_yaml(data), encoding="utf-8")
        written.append(path)
    return written


def _main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Emit Phase 7 concept skeletons.")
    parser.add_argument("out_dir", help="directory to write global.yaml + treasury.yaml")
    parser.add_argument("--force", action="store_true", help="overwrite existing files")
    args = parser.parse_args(argv)
    written = emit_skeletons(args.out_dir, force=args.force)
    for p in written:
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
