-- PRISMA_AUDIT_LOG — Treasury Studio denetim (audit) tablosu (Oturum 8 / H1).
-- Bir kez çalıştır (ya da kod tarafında `presentations.audit.ensure_table(dc)`).
-- Kim ne prompt yazdı, hangi tabloyu üretti, hangi query'yi yazdı, LLM'e ne gitti /
-- ne döndü, hangi session/kullanıcıyla bağlı — hepsi tek tabloda, session id ile.
--
-- NOT: bu DDL `presentations/audit.py` içindeki `DDL` sabitiyle BİREBİR aynı olmalı.

CREATE TABLE PRISMA_AUDIT_LOG (
  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EVENT_TS        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  USER_SICIL      VARCHAR2(32),
  SESSION_ID      VARCHAR2(64),
  PRESENTATION_ID VARCHAR2(64),
  REQUEST_ID      VARCHAR2(64),
  STAGE           VARCHAR2(24),
  EVENT_TYPE      VARCHAR2(48),
  PROMPT          CLOB,
  LLM_REQUEST     CLOB,
  LLM_RESPONSE    CLOB,
  SQL_TEXT        CLOB,
  TABLE_REF       VARCHAR2(256),
  META_JSON       CLOB,
  DURATION_MS     NUMBER,
  FINISH_REASON   VARCHAR2(32),
  ERROR_TEXT      CLOB
);

-- Tipik sorgular için indeksler (kullanıcı / sunum / zaman bazlı izleme).
CREATE INDEX IX_AUDIT_USER  ON PRISMA_AUDIT_LOG (USER_SICIL, EVENT_TS);
CREATE INDEX IX_AUDIT_PRES  ON PRISMA_AUDIT_LOG (PRESENTATION_ID, EVENT_TS);
CREATE INDEX IX_AUDIT_REQ   ON PRISMA_AUDIT_LOG (REQUEST_ID);
