"""Audit log (Oturum 8, Karar H) — kim ne prompt yazdı, hangi tabloyu üretti,
hangi query'yi yazdı, LLM'e ne gitti / ne döndü, hangi session/kullanıcıyla bağlı.

Olaylar Oracle ``PRISMA_AUDIT_LOG`` tablosuna yazılır (DDL: ``sql/audit_log_ddl.sql``,
``ensure_table`` ile de oluşturulur). Yazım **best-effort + async**: olay bir kuyruğa
konur, arka-plan worker batch'ler hâlinde `dc.get_connection` (raw oracledb DEĞİL —
DataClient'ın bağlantı mekanizması) ile yazar. Audit ASLA request'i yavaşlatmaz/
düşürmez — her hata yutulur. DEV/stub (get_connection yok) → sessiz no-op.

Kullanım (lazy singleton, app.py'ye dokunmaz):

    from presentations import audit
    audit.log_event("llm_chat", user_sicil=sicil, presentation_id=pid,
                    prompt=msg, llm_request=composed, llm_response=resp,
                    finish_reason=fr, duration_ms=ms)
"""
from __future__ import annotations

import json
import logging
import queue
import threading
import time
from dataclasses import dataclass, field

log = logging.getLogger(__name__)

AUDIT_TABLE = "PRISMA_AUDIT_LOG"

# CLOB alanları için güvenlik üst-sınırı (patholojik dev prompt'lar log'u şişirmesin).
_MAX_CLOB = 1_000_000

_INSERT_COLS = [
    "user_sicil", "session_id", "presentation_id", "request_id", "stage",
    "event_type", "prompt", "llm_request", "llm_response", "sql_text",
    "table_ref", "meta_json", "duration_ms", "finish_reason", "error_text",
]

INSERT_SQL = (
    f"INSERT INTO {AUDIT_TABLE} (USER_SICIL, SESSION_ID, PRESENTATION_ID, "
    "REQUEST_ID, STAGE, EVENT_TYPE, PROMPT, LLM_REQUEST, LLM_RESPONSE, SQL_TEXT, "
    "TABLE_REF, META_JSON, DURATION_MS, FINISH_REASON, ERROR_TEXT) VALUES "
    "(:user_sicil, :session_id, :presentation_id, :request_id, :stage, :event_type, "
    ":prompt, :llm_request, :llm_response, :sql_text, :table_ref, :meta_json, "
    ":duration_ms, :finish_reason, :error_text)"
)

# Oracle: CREATE TABLE'da IF NOT EXISTS yok → ensure_table ORA-00955'i yutar.
DDL = """
CREATE TABLE PRISMA_AUDIT_LOG (
  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EVENT_TS        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  USER_SICIL      VARCHAR2(32),
  SESSION_ID      VARCHAR2(64),
  PRESENTATION_ID VARCHAR2(64),
  REQUEST_ID      VARCHAR2(64),
  STAGE           VARCHAR2(24),
  EVENT_TYPE      VARCHAR2(48),
  PROMPT          CLOB,
  LLM_REQUEST     CLOB,
  LLM_RESPONSE    CLOB,
  SQL_TEXT        CLOB,
  TABLE_REF       VARCHAR2(256),
  META_JSON       CLOB,
  DURATION_MS     NUMBER,
  FINISH_REASON   VARCHAR2(32),
  ERROR_TEXT      CLOB
)
""".strip()


def _clip(v):
    if v is None:
        return None
    s = v if isinstance(v, str) else json.dumps(v, ensure_ascii=False, default=str)
    return s[:_MAX_CLOB]


@dataclass
class AuditLogger:
    dc: object
    enabled: bool = True
    batch_size: int = 25
    flush_interval: float = 5.0
    start_worker: bool = True        # test: False → kuyruk yarışı yok, flush() senkron
    _q: "queue.Queue" = field(default=None, init=False)
    _worker: threading.Thread = field(default=None, init=False)
    _stop: threading.Event = field(default=None, init=False)

    def __post_init__(self):
        self._q = queue.Queue(maxsize=10_000)
        self._stop = threading.Event()
        if self.enabled and self.start_worker:
            self._worker = threading.Thread(target=self._run, daemon=True,
                                            name="audit-log")
            self._worker.start()

    # ── Public API ────────────────────────────────────────────────────────────

    def log(self, event_type: str, **fields) -> None:
        """Bir olayı kuyruğa koy (best-effort, non-blocking). Kuyruk doluysa düşür."""
        if not self.enabled:
            return
        row = {c: None for c in _INSERT_COLS}
        row["event_type"] = (event_type or "")[:48]
        for k, v in fields.items():
            if k not in row:
                continue
            if k in ("prompt", "llm_request", "llm_response", "sql_text",
                     "meta_json", "error_text"):
                row[k] = _clip(v)
            elif k == "duration_ms":
                row[k] = int(v) if v is not None else None
            else:
                row[k] = None if v is None else str(v)[:256]
        # meta dict gelirse JSON'a çevir (meta_json alanına)
        if fields.get("meta") is not None and row["meta_json"] is None:
            row["meta_json"] = _clip(fields["meta"])
        try:
            self._q.put_nowait(row)
        except queue.Full:
            log.warning("audit: kuyruk dolu, olay düşürüldü (%s)", event_type)

    def flush(self, timeout: float = 5.0) -> int:
        """Kuyruğu SENKRON boşalt + yaz (test + kapatma). Yazılan satır sayısını döner."""
        batch = []
        while True:
            try:
                batch.append(self._q.get_nowait())
            except queue.Empty:
                break
        if batch:
            self._flush(batch)
        return len(batch)

    def close(self) -> None:
        self._stop.set()
        self.flush()

    # ── Internals ─────────────────────────────────────────────────────────────

    def _run(self) -> None:
        while not self._stop.is_set():
            batch = []
            try:
                batch.append(self._q.get(timeout=self.flush_interval))
            except queue.Empty:
                continue
            deadline = time.monotonic() + 0.5
            while len(batch) < self.batch_size and time.monotonic() < deadline:
                try:
                    batch.append(self._q.get_nowait())
                except queue.Empty:
                    break
            self._flush(batch)

    def _flush(self, batch: list) -> None:
        if not batch:
            return
        try:
            conn = self.dc.get_connection()
        except Exception:
            # DEV/stub'da get_connection yok → sessiz no-op (audit kritik değil).
            log.debug("audit: get_connection yok, %d olay yazılamadı", len(batch))
            return
        try:
            cur = conn.cursor()
            cur.executemany(INSERT_SQL, batch)
            conn.commit()
        except Exception:
            log.warning("audit: flush başarısız (best-effort, %d olay)",
                        len(batch), exc_info=True)
        finally:
            try:
                conn.close()
            except Exception:
                pass


def ensure_table(dc) -> bool:
    """``PRISMA_AUDIT_LOG`` yoksa oluştur (ORA-00955 'zaten var' yutulur). Ofis
    ilk kurulumda bir kez çağırabilir ya da DDL'i elle çalıştırır. Başarı/zaten-var
    → True; başka hata → False."""
    try:
        conn = dc.get_connection()
    except Exception:
        return False
    try:
        cur = conn.cursor()
        cur.execute(DDL)
        conn.commit()
        return True
    except Exception as exc:
        if "ORA-00955" in str(exc):   # name is already used by an existing object
            return True
        log.warning("audit: ensure_table başarısız: %s", exc)
        return False
    finally:
        try:
            conn.close()
        except Exception:
            pass


# ── Lazy app-singleton (app.py'ye dokunmadan) ─────────────────────────────────

_LOGGER = None
_LOGGER_LOCK = threading.Lock()


def get_logger():
    global _LOGGER
    if _LOGGER is None:
        with _LOGGER_LOCK:
            if _LOGGER is None:
                from flask import current_app
                dc = current_app.config.get("DATA_CLIENT")
                enabled = bool(current_app.config.get("AUDIT_ENABLED", True))
                _LOGGER = AuditLogger(dc, enabled=enabled)
    return _LOGGER


def log_event(event_type: str, **fields) -> None:
    """Hook noktalarının çağırdığı tek giriş. Audit ASLA request'i düşürmez."""
    try:
        get_logger().log(event_type, **fields)
    except Exception:
        pass


def _reset_for_test(logger=None):
    """Test yardımcısı — singleton'ı sıfırla/enjekte et."""
    global _LOGGER
    _LOGGER = logger
