WITH SRC_RSRV AS (
    SELECT * FROM EDW.DEP_PRC_RSRV
),
EKSTREM_YETKI AS (
    SELECT
        EKSTREM + (ZARAR_YETKISI / 100.0) AS EKSTREM_YETKI,
        DOVIZ AS EY_DOVIZ,
        VADE_BASLANGIC AS EY_VADE,
        DAT AS EY_DT
    FROM
        A16438.MEVDUAT_YETKILER
),
EDW_CUST AS (
    SELECT 
        CUST_ID AS CUST_ID_TP, 
        CUST_TP 
    FROM
        EDW.T_CUST
),
EDW_PORTFOLIO_AMT AS (
    SELECT
        CUST_PRTFL_AMT AS PORTFOLIO_AMT,
        CUST_ID AS CUST_ID_PORTFOLIO,
        PROCESS_DT
    FROM
        EDW.DEP_PRC_CUST
),
TREASURY_DATA AS (
    SELECT
        *
    FROM 
        SRC_RSRV
    LEFT JOIN
        EDW_CUST
    ON
        SRC_RSRV.CUST_ID = EDW_CUST.CUST_ID_TP
    LEFT JOIN
        EDW_PORTFOLIO_AMT
    ON
        SRC_RSRV.CUST_ID = EDW_PORTFOLIO_AMT.CUST_ID_PORTFOLIO
        AND SRC_RSRV.RSRVTN_DT = EDW_PORTFOLIO_AMT.PROCESS_DT
    LEFT JOIN 
        (SELECT ASOFDATE AS MARKET_MAX_DATE, MARKET_MAX_RT FROM A16438.DEP_SMALL_APP_PARAMS) market_max
    ON 
        SRC_RSRV.RSRVTN_DT = market_max.MARKET_MAX_DATE
    LEFT JOIN
        EKSTREM_YETKI
    ON
        SRC_RSRV.RSRVTN_DT = EKSTREM_YETKI.EY_DT
        AND SRC_RSRV.CURRENCY_CD = EKSTREM_YETKI.EY_DOVIZ
        AND SRC_RSRV.MTRTY_STRT = EKSTREM_YETKI.EY_VADE
)
SELECT
    TREASURY_DATA.*
FROM
    TREASURY_DATA
WHERE
    RSRVTN_DT >= TO_DATE('25/11/2025', 'DD/MM/YYYY')